# Generated by Django 2.1.5 on 2019-01-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='Value', null=True)),
            ],
            options={
                'db_table': 'SurveyAnswer',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'SurveyQuestionTemplate',
            },
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question',
            field=models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.SurveyQuestionTemplate'),
        ),
    ]
