# Generated by Django 2.1.5 on 2019-01-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190130_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionValueTemplate',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.TextField(db_column='Value')),
                ('label', models.TextField(db_column='Label')),
            ],
            options={
                'db_table': 'SurveyQuestionValueTemplate',
            },
        ),
        migrations.AddField(
            model_name='surveyquestiontemplate',
            name='class_name',
            field=models.CharField(db_column='ClassName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='class_name',
            field=models.TextField(db_column='ClassName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveystep',
            name='class_name',
            field=models.CharField(db_column='ClassName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionvaluetemplate',
            name='question',
            field=models.ForeignKey(db_column='OwnerID', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.SurveyQuestionTemplate'),
        ),
    ]
