# Generated by Django 2.1.5 on 2019-02-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190131_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestiontemplate',
            name='step',
            field=models.ForeignKey(db_column='StepID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.SurveyStepTemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestionvaluetemplate',
            name='question',
            field=models.ForeignKey(db_column='OwnerID', on_delete=django.db.models.deletion.CASCADE, related_name='value_options', to='reports.SurveyQuestionTemplate'),
        ),
    ]
