# Generated by Django 2.1.5 on 2019-02-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190201_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestiontemplate',
            old_name='step',
            new_name='step_template',
        ),
    ]
