# Generated by Django 2.1.5 on 2019-02-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190201_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='step',
            field=models.ForeignKey(db_column='StepID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.SurveyStep'),
            preserve_default=False,
        ),
    ]
