# Generated by Django 2.1.5 on 2019-02-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_surveyanswer_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.TextField(db_column='FirstName')),
                ('last_name', models.TextField(db_column='Surname')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(db_column='CreatedByID', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='reports.Member'),
            preserve_default=False,
        ),
    ]
