# Generated by Django 2.1.5 on 2019-02-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_surveyquestionvaluetemplate_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDropDownQuestionTemplate',
            fields=[
                ('surveyquestiontemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.SurveyQuestionTemplate')),
                ('is_multi_value', models.BooleanField(db_column='IsMultiSelect', default=0)),
                ('is_country_selector', models.BooleanField(db_column='IsCountrySelector', default=0)),
            ],
            options={
                'db_table': 'SurveyQuestionTemplate',
            },
            bases=('reports.surveyquestiontemplate',),
        ),
    ]
