# Generated by Django 2.1.5 on 2019-02-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_surveydropdownquestiontemplate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveydropdownquestiontemplate',
            table='SurveyDropDownQuestionTemplate',
        ),
    ]
