# Generated by Django 2.1.5 on 2019-02-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20190211_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitysurveytemplate',
            old_name='parent_survey_template',
            new_name='parent_template',
        ),
        migrations.AlterField(
            model_name='entitysurveytemplate',
            name='surveytemplate_ptr',
            field=models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.SurveyTemplate'),
        ),
    ]
