# Generated by Django 2.1.5 on 2019-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20190212_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='last_edited',
            field=models.DateTimeField(db_column='LastEdited', default=0),
            preserve_default=False,
        ),
    ]
