# Generated by Django 2.1.5 on 2019-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_survey_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='class_name',
            field=models.CharField(db_column='ClassName', default='SurveyTeplate', max_length=50),
            preserve_default=False,
        ),
    ]
