# Generated by Django 2.1.5 on 2019-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_surveytemplate_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestiontemplate',
            name='is_mandatory',
            field=models.BooleanField(db_column='Mandatory', default=0),
            preserve_default=False,
        ),
    ]
